feeds: 
  - psilocybinalpha: https://psilocybinalpha.com/feed
  - trufflereport: https://www.truffle.report/feed
  - cannabisstock: https://thecannabisstock.com/feed
  - psychedelicstockwatch: https://psychedelicstockwatch.com/index.rss
